### ISSUE TITLE
make Config.Credentials non-pointer member

### ISSUE THREAD

**Issue by alexanderwilling** [phrase/phraseapp-go#15]
Embedding the credentials as a pointer member is bad practice and bad UX because of nil-unsafety. See also: https://play.golang.org/p/5a84q61Es8

By embedding the credentials as a non-pointer member, a lot of nil-checking can be avoided entirely or at least replaced with more obvious non-default-checking on members of `Credentials`(/`Config` by embedding).

It might even make sense not to embed `Credentials` in `Config` but to just have it be a normal member.

**Comment by tobstarr** [comment]
I do not like embedding at all so good for me (also to not embed in the first place)
