### ISSUE TITLE
is there plan to support context?

### ISSUE THREAD

**Issue by vincent178** [phrase/phraseapp-go#55]
We're using phrase for translation, when integrate using API, I'd like to pass in context for two purpose:
1. easily tracing with honeycomb, honeycomb requires context to store/fetch tracing information.
2. easily do timeout control, with context, it's very easy to set timeout for a call.

I'd like to know is there a plan to support context when send request?

Thanks!

**Comment by theSoenke** [comment]
Hi @vincent178, we don't have any plans right now to add context support. But I definitely see the value of it. We are considering changing how the library is auto generated. And hopefully during that we will be able to support passing the context along. I will definitely take this into consideration and will keep you updated there when there is an update

**Comment by vincent178** [comment]
Thanks @theSoenke for the response, looking forward to the new implementation.

**Comment by theSoenke** [comment]
Hi @vincent178, we have now released a new library phrase-go where it is possible to pass in a context  https://github.com/phrase/phrase-go
