### ISSUE TITLE
docs and examples

### ISSUE THREAD

**Issue by jfragosoperez** [phrase/phraseapp-go#6]
There is no docs neither examples of the usage of the API. It's required a lot of time checking the big files line per line to figure out where are your needed features located. 
I am in favour of going deeply into the code before integrating any API/SDK, but having quick reference documentation is always good, specially in languages such as Golang where sadly and up to this moment, IDEs are not enough integrated to the language and there is no "jump into the code" feature, which makes tools like Dash an essential tool for quick ref. My mate @ramonmacias and I have spent  a lot of time creating little examples and going through the code, I think this would be something pretty good for gaining new customers that want to quickly integrate your translations system into theirs.

**Comment by kennell** [comment]
Hi @jfragosoperez - thanks for your input. We agree and will be adding some usage examples and documentation for this library soon. If you have any specific examples that you have found to be useful, feel free to share them here.

**Comment by jfragosoperez** [comment]
Hi @kennell that's really good news. I'll post some of the wrapper methods and docs we've been writing in our integration ASAP. We first need to face on our dev. planning for this week, so I guess it'll be in some moment along this weekend. I'll keep you updated, hope our code can be some kind of help for you.

**Comment by jfragosoperez** [comment]
Hey, I am sorry about not giving any feedback since then. I am planning to add this examples and docs in the middle of next months, we're crowded by deliveries and haven't had a while to do it yet. Apologies for delaying in the answer, we'll do everything we can to help as soon as we can.

**Comment by sacry-dyn** [comment]
@jfragosoperez no worries! We are probably as busy as you and looking forward to your samples!

**Comment by sacry-dyn** [comment]
@jfragosoperez hey! Hope all is going well. Is there any update on this issue? I would like to resolve it in the near future. Maybe you already have some samples and I can start integrating a section by your samples to push this topic. :)

**Comment by jfragosoperez** [comment]
hi @sacry-dyn we're still busy. If you have added this issue to your roadmap willing to solve it soon, you can start adding some samples and docs. Tell me something once you've finished and I'll check and compare the helper methods and examples and, if you forgot to add something, I'll provide the contents. So if the priority to solve this issue is high, start and I'll join with more examples when everything is more calmed down, which will be probably when I'll be on work holidays. Thanks and apologies for the inconveniences

**Comment by sacry-dyn** [comment]
@jfragosoperez no worries! We will make a small script that will show some basic samples on how to use the library. Will come back to you when we have something.

**Comment by theSoenke** [comment]
It took some time but we finally have some examples on how to use the library :sweat_smile:
Small code examples can be found in the Readme. For a more complete example you can have a look at the wiki with an example how to upload files as translations https://github.com/phrase/phraseapp-go/wiki/Sync-local-files-to-PhraseApp

I tried to add an example for most common use cases. Let us know if there is anything important missing for you
