### ISSUE TITLE
Have per project config override per user configuration

### ISSUE THREAD

**Issue by maufl** [phrase/phraseapp-go#7]
I would like to be able to set my access token in `~/.phraseapp.yml` and the rest of the configuration in `project/.phraseapp.yml`. The configuration in the project is commited to Git and shared between all developers, so we can not set an access token there.

Alternatively we would have to commit the `.pharseapp.yml` without access token, then ignore it and have each user change the configuration.

**Comment by sacry-dyn** [comment]
Hi @maufl have you tried setting the `PHRASEAPP_ACCESS_TOKEN` via env leaving out the `access_token` in your configuration? Or do you need a different mechanism setting the token? (could you clarify if so)

**Comment by maufl** [comment]
I tried it just now and it works. We could write a wrapper script that reads the token from a file, always providing it on the command line is not a nice solution. I still think it would be nice if configuration would be read from $HOME if it is missing in the project, just like Git does it. But it's not required by us, so if you want you can close this issue.

**Comment by docstun** [comment]
@maufl you don't need to provide it from the command line, just export the variable to your environment and you should be good to go.

**Comment by maufl** [comment]
You're right, we'll do something like that.

**Comment by sacry-dyn** [comment]
Okay, great. We will close the issue for now. Feel free to reopen (or make a new one) if the need arises.
